stack = [ ]
stack.append('AMIT')
stack.append('BHAKTI')
stack.append('CHETAN')
print('Initial stack')
print(stack)
print('\nElements popped from stack:')
print(stack.pop())
print(stack.pop())
print('\nStack after elements are popped:')
print(stack)
